/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UniverseSimulator */

#ifndef _Included_UniverseSimulator
#define _Included_UniverseSimulator
#ifdef __cplusplus
extern "C" {
#endif
#undef UniverseSimulator_FOCUS_TRAVERSABLE_UNKNOWN
#define UniverseSimulator_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef UniverseSimulator_FOCUS_TRAVERSABLE_DEFAULT
#define UniverseSimulator_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef UniverseSimulator_FOCUS_TRAVERSABLE_SET
#define UniverseSimulator_FOCUS_TRAVERSABLE_SET 2L
#undef UniverseSimulator_TOP_ALIGNMENT
#define UniverseSimulator_TOP_ALIGNMENT 0.0f
#undef UniverseSimulator_CENTER_ALIGNMENT
#define UniverseSimulator_CENTER_ALIGNMENT 0.5f
#undef UniverseSimulator_BOTTOM_ALIGNMENT
#define UniverseSimulator_BOTTOM_ALIGNMENT 1.0f
#undef UniverseSimulator_LEFT_ALIGNMENT
#define UniverseSimulator_LEFT_ALIGNMENT 0.0f
#undef UniverseSimulator_RIGHT_ALIGNMENT
#define UniverseSimulator_RIGHT_ALIGNMENT 1.0f
#undef UniverseSimulator_serialVersionUID
#define UniverseSimulator_serialVersionUID -7644114512714619750LL
#undef UniverseSimulator_serialVersionUID
#define UniverseSimulator_serialVersionUID 4613797578919906343LL
#undef UniverseSimulator_INCLUDE_SELF
#define UniverseSimulator_INCLUDE_SELF 1L
#undef UniverseSimulator_SEARCH_HEAVYWEIGHTS
#define UniverseSimulator_SEARCH_HEAVYWEIGHTS 1L
#undef UniverseSimulator_OPENED
#define UniverseSimulator_OPENED 1L
#undef UniverseSimulator_serialVersionUID
#define UniverseSimulator_serialVersionUID 4497834738069338734LL
#undef UniverseSimulator_DEFAULT_CURSOR
#define UniverseSimulator_DEFAULT_CURSOR 0L
#undef UniverseSimulator_CROSSHAIR_CURSOR
#define UniverseSimulator_CROSSHAIR_CURSOR 1L
#undef UniverseSimulator_TEXT_CURSOR
#define UniverseSimulator_TEXT_CURSOR 2L
#undef UniverseSimulator_WAIT_CURSOR
#define UniverseSimulator_WAIT_CURSOR 3L
#undef UniverseSimulator_SW_RESIZE_CURSOR
#define UniverseSimulator_SW_RESIZE_CURSOR 4L
#undef UniverseSimulator_SE_RESIZE_CURSOR
#define UniverseSimulator_SE_RESIZE_CURSOR 5L
#undef UniverseSimulator_NW_RESIZE_CURSOR
#define UniverseSimulator_NW_RESIZE_CURSOR 6L
#undef UniverseSimulator_NE_RESIZE_CURSOR
#define UniverseSimulator_NE_RESIZE_CURSOR 7L
#undef UniverseSimulator_N_RESIZE_CURSOR
#define UniverseSimulator_N_RESIZE_CURSOR 8L
#undef UniverseSimulator_S_RESIZE_CURSOR
#define UniverseSimulator_S_RESIZE_CURSOR 9L
#undef UniverseSimulator_W_RESIZE_CURSOR
#define UniverseSimulator_W_RESIZE_CURSOR 10L
#undef UniverseSimulator_E_RESIZE_CURSOR
#define UniverseSimulator_E_RESIZE_CURSOR 11L
#undef UniverseSimulator_HAND_CURSOR
#define UniverseSimulator_HAND_CURSOR 12L
#undef UniverseSimulator_MOVE_CURSOR
#define UniverseSimulator_MOVE_CURSOR 13L
#undef UniverseSimulator_NORMAL
#define UniverseSimulator_NORMAL 0L
#undef UniverseSimulator_ICONIFIED
#define UniverseSimulator_ICONIFIED 1L
#undef UniverseSimulator_MAXIMIZED_HORIZ
#define UniverseSimulator_MAXIMIZED_HORIZ 2L
#undef UniverseSimulator_MAXIMIZED_VERT
#define UniverseSimulator_MAXIMIZED_VERT 4L
#undef UniverseSimulator_MAXIMIZED_BOTH
#define UniverseSimulator_MAXIMIZED_BOTH 6L
#undef UniverseSimulator_serialVersionUID
#define UniverseSimulator_serialVersionUID 2673458971256075116LL
#undef UniverseSimulator_LIGHT_YEAR
#define UniverseSimulator_LIGHT_YEAR 9.461E15
#undef UniverseSimulator_YEAR_SECONDS
#define UniverseSimulator_YEAR_SECONDS 3.15576E7
/*
 * Class:     UniverseSimulator
 * Method:    initSimulation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_initSimulation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     UniverseSimulator
 * Method:    stepSimulation
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_stepSimulation
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     UniverseSimulator
 * Method:    resetSimulation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_resetSimulation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     UniverseSimulator
 * Method:    setTimeScale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_setTimeScale
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     UniverseSimulator
 * Method:    setPaused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_setPaused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     UniverseSimulator
 * Method:    getUniverseAge
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_UniverseSimulator_getUniverseAge
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getParticleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UniverseSimulator_getParticleCount
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getStarCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UniverseSimulator_getStarCount
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getGalaxyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UniverseSimulator_getGalaxyCount
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getScaleFactor
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_UniverseSimulator_getScaleFactor
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getHubbleConstant
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_UniverseSimulator_getHubbleConstant
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getEpoch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_UniverseSimulator_getEpoch
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getParticleData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_UniverseSimulator_getParticleData
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getUniverseParams
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_UniverseSimulator_getUniverseParams
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    getPhotonData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_UniverseSimulator_getPhotonData
  (JNIEnv *, jobject);

/*
 * Class:     UniverseSimulator
 * Method:    initRenderer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_initRenderer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     UniverseSimulator
 * Method:    resizeRenderer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_resizeRenderer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     UniverseSimulator
 * Method:    setCameraOrbit
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_setCameraOrbit
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     UniverseSimulator
 * Method:    setRenderMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_setRenderMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     UniverseSimulator
 * Method:    renderFrame
 * Signature: ([ID)V
 */
JNIEXPORT void JNICALL Java_UniverseSimulator_renderFrame
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
